### ISSUE TITLE
Ball will go crazy after falling a long time

### ISSUE THREAD

**Issue by littlecatberry** [DranKof/Ballblastic#12]
After the ball falls off the board, the shadow  shows up incorrectly .

**Comment by DranKof** [comment]
Yeah, I'm guessing this is probably because the ball is falling so fast that it's "outrunning" the shadow renderer. Sometimes the ball just up and disappears for me too. We just need to find a way to avoid super high speeds. Will definitely adjust this.

**Comment by DranKof** [comment]
Fixed 96f68d3c2620940f770ecbb72055eae91e499f76
