### ISSUE TITLE
You should rename this ball blast...or anything else.

### ISSUE THREAD

**Issue by littlecatberry** [DranKof/Ballblastic#13]
There were like 100 "ballast"s on GitHub...and it still sounds like something ship-oriented.

**Comment by DranKof** [comment]
Game will be renamed to Ball Blastastic. Repository already renamed, next is renaming the files next time I'm coding.

**Comment by DranKof** [comment]
Fixed 96f68d3c2620940f770ecbb72055eae91e499f76
Final Name Change: Ballblastic

**Comment by DranKof** [comment]
Zombification post:
Apparently there was already a Ballastic on Steam which still felt too similar so I decided I'd change the game name one last time to Ballblastia (will have a good reason why, too)!
